In [3]:
import numpy as np

#матриці
M = np.array([[100,150,200,],
             [50,100,150],
             [0,50,100]])

E = np.array([[20,30,40],
             [10,20,30],
             [5,10,15]])

#зміна контр множення на скаляр 0.5
result_1_1 = 0.5 * M
print("1.1 Зміна контрасту(0.5* М):")
print(result_1_1)

#корекція яскравості додавання скаляр 25
result_1_2 = 25 + M
print("\n1.2 Корекція яскравості(25 + М):")
print(result_1_2)

#змішування 0.8 * М + 0.2 * Е
result_1_3 = 0.8 * M + 0.2 * E
print("\n1.3 Змішування(0.8 * М + 0.2 * Е):")
print(result_1_3)


1.1 Зміна контрасту(0.5* М):
[[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]

1.2 Корекція яскравості(25 + М):
[[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

1.3 Змішування(0.8 * М + 0.2 * Е):
[[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


In [11]:
import numpy as np
from numpy.linalg import norm

user = np.array([8, 2, 5])      #користувач
Va = np.array([9, 1, 2])        #action
Vb = np.array([1, 9, 8])        #comedy
Vc = np.array([7, 2, 6])        #drama

#список фільмів
movies = {
    "Action": Va,
    "Comedy": Vb,
    "Drama": Vc
}

print("Результат:")

#рахуємо косинус кожного фільму
for name, vector in movies.items():
    #скалярний добуток
    dot_product = np.dot(user, vector)

    #довжина векторів 
    norm_user = norm(user)
    norm_movie = norm(vector)

    #косинус кута (cos theta)
    cosine = dot_product / (norm_user * norm_movie)

    #кут у градусах (через arccos)
    angle_rad = np.arccos(cosine)
    angle_deg = np.degrees(angle_rad)

    print(f"Фільм {name}: Cos = {cosine:.2f}, Кут = {angle_deg:.0f}°")

print("\nФільм Vc(drama) має найбільшу схожість з вподобаннями користувача")

Результат:
Фільм Action: Cos = 0.94, Кут = 20°
Фільм Comedy: Cos = 0.57, Кут = 56°
Фільм Drama: Cos = 0.99, Кут = 8°

Фільм Vc(drama) має найбільшу схожість з вподобаннями користувача


In [12]:
import numpy as np
#аналіз виробництва (Ax = b)
#матриця A
A = np.array([[4, 1, 1],
              [4, 1, 2],
              [6, 2, 4]])

#вектор b
b = np.array([460, 130, 240])

x = np.linalg.solve(A, b)

print("Результат виробництва:")
print(f"x1 = {x[0]:.0f}")
print(f"x2 = {x[1]:.0f}")
print(f"x3 = {x[2]:.0f}")
print()

Результат виробництва:
x1 = 10
x2 = 750
x3 = -330



In [13]:
import numpy as np

#прогноз тренду(y = kx + b)

t = np.array([1, 2, 3, 4, 5])       #сас
y = np.array([22, 28, 37, 45, 53])  #навантаження

k, b_param = np.polyfit(t, y, 1)

#прогноз на 6-ту годину
t_forecast = 6
y_forecast = k * t_forecast + b_param

print("Результат прогнозу тренду:")
print(f"Рівняння тренду: y = {k:.2f}x + {b_param:.2f}")
print(f"Прогноз навантаження на 6-ту годину: {y_forecast:.2f}")

Результат прогнозу тренду:
Рівняння тренду: y = 7.90x + 13.30
Прогноз навантаження на 6-ту годину: 60.70
